version: '3'

services:
  django:
    build: .
    env_file:
      - ./project.env
    command: supervisord -n -c deploy/supervisor.conf
    volumes:
      - .:/opt/django
      - ./deploy/db:/var/lib/django
      - /etc/letsencrypt:/etc/letsencrypt
      - ./deploy/static:/var/www/static
      - ./deploy/media:/var/www/media
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: "50m"
        max-file: "2"